duraark-digitalpreservation:
  # image: duraark/duraark-digitalpreservation:0.7.0
  build: .
  command: nodemon --watch /duraark/microservice/api -w /duraark/microservice/config app.js
  ports:
    - "5015:5015"
#  If you are also using the 'duraark-sessions' service use 'volumes_from'
#  instead of /duraark-storage entry in the 'volumes' section below to link
#  to the file storage.
#  volumes-from:
#    - duraark-sessions
  volumes:
    - .:/duraark/microservice
    - /tmp/files:/duraark-storage # remove this line if you use the 'duraark-sessions' service
